"""Iniial check

Revision ID: 7f31a3047343
Revises: 
Create Date: 2024-02-20 20:38:37.163306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f31a3047343'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('__access_token', sa.String(), nullable=False),
    sa.Column('__refresh_token', sa.String(), nullable=False),
    sa.Column('coupon', sa.String(), nullable=False),
    sa.Column('special_field', sa.JSON(), nullable=False),
    sa.Column('fake_points', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('cvc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('payment_field', sa.JSON(), nullable=False),
    sa.Column('__account_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['__account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rides')
    op.drop_table('cards')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
